// Ambient declaration for CSS side-effect imports (react-grid-layout/css/styles.css,
// react-resizable/css/styles.css in app/layout.tsx). Next.js ships this same
// declaration in its own global.d.ts, but only next-env.d.ts references it — and
// next-env.d.ts is gitignored, auto-generated by `next dev`/`next build`. CI's
// typecheck step runs plain `tsc --noEmit` without ever invoking the Next CLI first,
// so on a fresh checkout next-env.d.ts doesn't exist yet and tsc has no declaration
// for these imports (TS2882). Declaring it ourselves removes that dependency.
declare module '*.css'
