// Client-safe view engine surface: descriptors (1b), Zustand store factories +
// persisted session/UI stores (1b), and client renderers (1c). The server loader /
// RSC dispatcher (1c) is server-only and lives behind the package `server.ts` barrel.
export * from './descriptor'
export * from './report-descriptor'
export * from './report-renderer'
export * from './report-chrome'
export * from './menu-actions'
export * from './form-actions-menu'
export * from './report-export'
export * from './behaviors'
export * from './stores'
export * from './session-store'
export * from './ui-store'
export * from './format-store'
export * from './palette'
export * from './tokens'
export * from './theme'
export * from './error-alert'
export * from './renderers'
export * from './picture-widgets'
export * from './relation-ops'
export * from './relation-widgets'
export * from './graph-ops'
export * from './notebook-ops'
export * from './recently-changed-store'
export * from './record-label-store'
export * from './icons'
export * from './saved-filter-ops'
export * from './search-bar'
